# Generated by Django 4.2.11 on 2026-01-14 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=255)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('breaking', 'Breaking News')], default='normal', max_length=20)),
                ('language', models.CharField(choices=[('bn', 'বাংলা (Bangla)'), ('en', 'English'), ('hi', 'हिन्दी (Hindi)'), ('ar', 'عربى (Arabic)')], default='bn', max_length=10)),
                ('is_event', models.BooleanField(default=False)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, max_length=255)),
                ('event_speakers', models.TextField(blank=True, help_text='Comma separated speaker names')),
                ('is_research', models.BooleanField(default=False)),
                ('research_topic', models.CharField(blank=True, max_length=255)),
                ('research_department', models.CharField(blank=True, max_length=100)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='news/thumbnails/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='news/banners/')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='news/attachments/')),
                ('author', models.CharField(default='গবেষণা বিভাগ (Research Department)', max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newscategory')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
