# Generated by Django 4.2.11 on 2026-02-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content_alter_news_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
            ],
            options={
                'verbose_name': 'Event/Seminar',
                'verbose_name_plural': 'Events & Seminars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.news',),
        ),
    ]
