# Generated by Django 4.2.11 on 2026-01-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='pi-users', help_text='PrimeNG icon class', max_length=50)),
                ('color', models.CharField(default='bg-blue-100 text-blue-800', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('designation', models.CharField(choices=[('professor', 'অধ্যাপক (Professor)'), ('associate_professor', 'সহযোগী অধ্যাপক (Associate Professor)'), ('assistant_professor', 'সহকারী অধ্যাপক (Assistant Professor)'), ('lecturer', 'প্রভাষক (Lecturer)'), ('research_fellow', 'গবেষণা ফেলো (Research Fellow)'), ('research_assistant', 'গবেষণা সহকারী (Research Assistant)'), ('administrative_officer', 'প্রশাসনিক কর্মকর্তা (Administrative Officer)'), ('accountant', 'হিসাবরক্ষক (Accountant)'), ('librarian', 'গ্রন্থাগারিক (Librarian)'), ('technical_staff', 'প্রযুক্তিগত কর্মী (Technical Staff)'), ('support_staff', 'সাহায্যকারী কর্মী (Support Staff)'), ('other', 'অন্যান্য (Other)')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short biography/description')),
                ('qualifications', models.TextField(blank=True, help_text='Educational qualifications')),
                ('research_interests', models.TextField(blank=True, help_text='Research interests')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff/profiles/')),
                ('cv', models.FileField(blank=True, help_text='PDF format preferred', null=True, upload_to='staff/cvs/')),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('google_scholar', models.URLField(blank=True)),
                ('researchgate', models.URLField(blank=True)),
                ('orcid', models.CharField(blank=True, max_length=50)),
                ('office_room', models.CharField(blank=True, max_length=50)),
                ('office_hours', models.TextField(blank=True, help_text='Office hours/days')),
                ('is_active', models.BooleanField(default=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staff.department')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Experience',
                'verbose_name_plural': 'Staff Experience',
                'ordering': ['-start_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='StaffEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('year', models.CharField(help_text='e.g., 2010-2014, 2020', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Education',
                'verbose_name_plural': 'Staff Education',
                'ordering': ['-year', 'display_order'],
            },
        ),
    ]
