# Generated by Django 4.2.11 on 2026-01-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(default='bg-blue-100 text-blue-800', max_length=40),
        ),
    ]
