# Generated by Django 4.2.11 on 2026-01-24 11:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0002_remove_userprofile_bio_userprofile_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bangla', models.CharField(help_text='চেয়ারম্যানের পূর্ণ নাম বাংলায়', max_length=255, verbose_name='নাম (বাংলা)')),
                ('name_english', models.CharField(help_text='Full name in English', max_length=255, verbose_name='Name (English)')),
                ('designation_bangla', models.CharField(help_text='উদাহরণ: পরিচালক, নাজমুল করিম স্টাডি সেন্টার', max_length=255, verbose_name='পদবী (বাংলা)')),
                ('designation_english', models.CharField(help_text='Example: Director, Nazmul Karim Study Center', max_length=255, verbose_name='Designation (English)')),
                ('bio_bangla', models.TextField(help_text='চেয়ারম্যানের সংক্ষিপ্ত জীবনবৃত্তান্ত বাংলায়', verbose_name='সংক্ষিপ্ত পরিচিতি (বাংলা)')),
                ('bio_english', models.TextField(help_text='Brief biography in English', verbose_name='Brief Biography (English)')),
                ('qualifications', models.TextField(blank=True, help_text='List of academic qualifications (one per line)', verbose_name='Academic Qualifications')),
                ('current_positions', models.TextField(blank=True, help_text='Current positions held (one per line)', verbose_name='Current Positions')),
                ('previous_positions', models.TextField(blank=True, help_text='Previous important positions (one per line)', verbose_name='Previous Positions')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('profile_image', models.ImageField(blank=True, help_text='Recommended size: 400x400 pixels', null=True, upload_to='chairman/profile/', verbose_name='Profile Image')),
                ('signature_image', models.ImageField(blank=True, help_text='Digital signature of chairman', null=True, upload_to='chairman/signature/', verbose_name='Signature Image')),
                ('cv_pdf', models.FileField(blank=True, help_text='Upload PDF file of complete CV', null=True, upload_to='chairman/cv/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Curriculum Vitae (PDF)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which chairman appears (lower number shows first)', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to display on website', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenure_start', models.DateField(blank=True, null=True, verbose_name='Tenure Start Date')),
                ('tenure_end', models.DateField(blank=True, help_text='Leave empty if currently serving', null=True, verbose_name='Tenure End Date')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profile')),
                ('researchgate_url', models.URLField(blank=True, verbose_name='ResearchGate Profile')),
                ('google_scholar_url', models.URLField(blank=True, verbose_name='Google Scholar Profile')),
                ('website_url', models.URLField(blank=True, verbose_name='Personal Website')),
            ],
            options={
                'verbose_name': 'Chairman',
                'verbose_name_plural': 'Chairmen',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChairmanUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_note', models.TextField(blank=True, help_text='Brief description of changes made', verbose_name='Update Note')),
                ('changes_json', models.JSONField(help_text='JSON representation of changes', verbose_name='Changes Made')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to='user_management.chairman')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Update History',
                'verbose_name_plural': 'Update Histories',
                'ordering': ['-updated_at'],
            },
        ),
    ]
