# Generated by Django 4.2.11 on 2026-01-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_chairman_chairmanupdatehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chairman',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Chairman', 'verbose_name_plural': 'Chairmen'},
        ),
        migrations.RemoveField(
            model_name='chairman',
            name='cv_pdf',
        ),
        migrations.RemoveField(
            model_name='chairman',
            name='google_scholar_url',
        ),
        migrations.RemoveField(
            model_name='chairman',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='chairman',
            name='researchgate_url',
        ),
        migrations.RemoveField(
            model_name='chairman',
            name='tenure_end',
        ),
        migrations.RemoveField(
            model_name='chairman',
            name='tenure_start',
        ),
        migrations.RemoveField(
            model_name='chairman',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='chairman',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers display first', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this chairman on the website', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='chairman/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='qualifications',
            field=models.TextField(blank=True, help_text='List academic qualifications (one per line)', verbose_name='Academic Qualifications'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='chairman/signature/', verbose_name='Signature'),
        ),
        migrations.DeleteModel(
            name='ChairmanUpdateHistory',
        ),
    ]
