# Generated by Django 4.2.11 on 2026-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_chairman_options_remove_chairman_cv_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='bio_english',
            field=models.TextField(default=False, help_text='Brief biography in English', null=True, verbose_name='Brief Biography (English)'),
        ),
    ]
