# Generated by Django 4.2.11 on 2026-01-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('issue', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=255)),
                ('issn', models.CharField(blank=True, max_length=50)),
                ('doi_url', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('pages', models.PositiveIntegerField()),
                ('file_size_mb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pdf_file', models.FileField(upload_to='journals/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='journal_previews/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
