# Generated by Django 4.2.11 on 2026-01-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Journal', 'verbose_name_plural': 'Journals'},
        ),
    ]
