# Generated by Django 4.2.11 on 2026-01-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={},
        ),
    ]
