# Generated by Django 4.2.11 on 2026-01-18 11:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('section_type', models.CharField(choices=[('history', 'ইতিহাস (History)'), ('development', 'প্রাতিষ্ঠানিক উন্নয়ন (Development)'), ('recognition', 'স্বীকৃতি (Recognition)'), ('mission', 'অভিলক্ষ্য (Mission)'), ('vision', 'দৃষ্টিভঙ্গি (Vision)'), ('facilities', 'সুবিধা (Facilities)'), ('directors', 'পরিচালক (Directors)'), ('timeline', 'সময়রেখা (Timeline)')], max_length=50)),
                ('icon', models.CharField(default='pi-info-circle', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('address', 'ঠিকানা'), ('email', 'ইমেইল'), ('phone', 'ফোন'), ('fax', 'ফ্যাক্স'), ('office_hours', 'অফিস সময়')], max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'ordering': ['display_order', 'contact_type'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('director_type', models.CharField(choices=[('current', 'বর্তমান পরিচালক (Current)'), ('previous', 'সাবেক পরিচালক (Previous)')], default='current', max_length=50)),
                ('period', models.CharField(help_text='e.g., ২০২০ - ২০২৫', max_length=100)),
                ('bio', ckeditor.fields.RichTextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/directors/')),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
                'ordering': ['director_type', '-display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='pi-building', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('capacity', models.CharField(blank=True, help_text='e.g., 50 persons, 1000 books', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/facilities/')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('prefix', models.CharField(blank=True, help_text='e.g., +', max_length=10)),
                ('suffix', models.CharField(blank=True, help_text='e.g., +, yrs', max_length=10)),
                ('icon', models.CharField(default='pi-chart-line', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='pi-calendar', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/timeline/')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['-display_order', 'year'],
            },
        ),
    ]
