# Generated by Django 4.2.11 on 2026-01-30 14:44

from django.db import migrations, models
import django.db.models.deletion
import media_stuff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('seminar', 'সেমিনার (Seminar)'), ('workshop', 'ওয়ার্কশপ (Workshop)'), ('conference', 'কনফারেন্স (Conference)'), ('cultural', 'সাংস্কৃতিক অনুষ্ঠান (Cultural Event)'), ('award', 'পুরস্কার বিতরণী (Award Ceremony)'), ('training', 'প্রশিক্ষণ (Training)'), ('other', 'অন্যান্য (Other)')], max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which category appears')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the event (e.g., 'Annual Seminar 2023')", max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('description', models.TextField(help_text='Full description of the event')),
                ('short_description', models.TextField(help_text='Brief description (max 200 characters) shown in listings', max_length=200)),
                ('event_date', models.DateField(help_text='Date when the event took place')),
                ('location', models.CharField(help_text="Venue location (e.g., 'NKSC Auditorium')", max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft - Not visible on website'), ('published', 'Published - Visible on website'), ('featured', 'Featured - Highlighted on website')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Check to feature this event on homepage')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Select event category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='media_stuff.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Event',
                'verbose_name_plural': 'Gallery Events',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='Paste YouTube or Vimeo video URL')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('other', 'Other')], default='youtube', editable=False, max_length=20)),
                ('title', models.CharField(help_text='Title for the video', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description for the video')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which video appears')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Select the event for this video', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='media_stuff.galleryevent')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload image (Recommended size: 1200x800px)', upload_to=media_stuff.models.gallery_image_path)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which image appears (lower numbers first)')),
                ('is_cover', models.BooleanField(default=False, help_text='Check to set as cover image for the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Select the event for these images', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='media_stuff.galleryevent')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
